coins_to_return = float(input())
coins_counter = 0
change_in_coins = int(coins_to_return * 100)
while change_in_coins > 0:
    if change_in_coins >= 200:
        change_in_coins -= 200
        coins_counter += 1
    elif change_in_coins >= 100:
        change_in_coins -= 100
        coins_counter += 1
    elif change_in_coins >= 50:
        change_in_coins -= 50
        coins_counter += 1
    elif change_in_coins >= 20:
        change_in_coins -= 20
        coins_counter += 1
    elif change_in_coins >= 10:
        change_in_coins -= 10
        coins_counter += 1
    elif change_in_coins >= 5:
        change_in_coins -= 5
        coins_counter += 1
    elif change_in_coins >= 2:
        change_in_coins -= 2
        coins_counter += 1
    elif change_in_coins >= 1:
        change_in_coins -= 1
        coins_counter += 1
print(coins_counter)
